import type { Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import Link from 'next/link'
import ConvexClientProvider from './providers/ConvexClientProvider'
import ThemeProvider from './providers/ThemeProvider'
import './style/main.css'

export const metadata: Metadata = {
  title: 'Wish app',
  description: 'Generated by hono',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ClerkProvider>
          <ThemeProvider>
            <ConvexClientProvider>
              {/* <Link href="/">home</Link> */}
              {children}
            </ConvexClientProvider>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  )
}
