import type { Metadata } from 'next'
import { ConvexClientProvider } from './providers/ConvexClientProvider'

export const metadata: Metadata = {
  title: 'Hono | nextjs',
  description: 'Generated by hono',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <ConvexClientProvider>{children}</ConvexClientProvider>
      </body>
    </html>
  )
}
