import "./style/main.css";

import { GeistSans } from 'geist/font/sans';

import type { Metadata } from "next";

import { Toaster } from "@/components/ui/sonner";
import { ClerkProvider } from "@clerk/nextjs";

import ConvexClientProvider from "./providers/ConvexClientProvider";
import ThemeProvider from "./providers/ThemeProvider";

export const metadata: Metadata = {
  title: "Wish app",
  description: "Generated by hono",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={GeistSans.className}>
      <body>
        <ClerkProvider>
          <ThemeProvider>
            <ConvexClientProvider>
              {children}
              <Toaster />
            </ConvexClientProvider>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
