/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardWaitlistRouteImport } from './routes/dashboard.waitlist'
import { Route as DashboardStatsRouteImport } from './routes/dashboard.stats'
import { Route as ChangelogSlugRouteImport } from './routes/changelog.$slug'
import { Route as DashboardProjectProjectIdSlugRouteImport } from './routes/dashboard.project.$projectId.$slug'
import { Route as DashboardProjectProjectIdSlugComplaintsRouteImport } from './routes/dashboard.project.$projectId.$slug.complaints'
import { Route as DashboardProjectProjectIdSlugChangelogRouteImport } from './routes/dashboard.project.$projectId.$slug.changelog'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWaitlistRoute = DashboardWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStatsRoute = DashboardStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => DashboardRoute,
} as any)
const ChangelogSlugRoute = ChangelogSlugRouteImport.update({
  id: '/changelog/$slug',
  path: '/changelog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectProjectIdSlugRoute =
  DashboardProjectProjectIdSlugRouteImport.update({
    id: '/project/$projectId/$slug',
    path: '/project/$projectId/$slug',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProjectProjectIdSlugComplaintsRoute =
  DashboardProjectProjectIdSlugComplaintsRouteImport.update({
    id: '/complaints',
    path: '/complaints',
    getParentRoute: () => DashboardProjectProjectIdSlugRoute,
  } as any)
const DashboardProjectProjectIdSlugChangelogRoute =
  DashboardProjectProjectIdSlugChangelogRouteImport.update({
    id: '/changelog',
    path: '/changelog',
    getParentRoute: () => DashboardProjectProjectIdSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/dashboard/waitlist': typeof DashboardWaitlistRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/project/$projectId/$slug': typeof DashboardProjectProjectIdSlugRouteWithChildren
  '/dashboard/project/$projectId/$slug/changelog': typeof DashboardProjectProjectIdSlugChangelogRoute
  '/dashboard/project/$projectId/$slug/complaints': typeof DashboardProjectProjectIdSlugComplaintsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/dashboard/waitlist': typeof DashboardWaitlistRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/project/$projectId/$slug': typeof DashboardProjectProjectIdSlugRouteWithChildren
  '/dashboard/project/$projectId/$slug/changelog': typeof DashboardProjectProjectIdSlugChangelogRoute
  '/dashboard/project/$projectId/$slug/complaints': typeof DashboardProjectProjectIdSlugComplaintsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/dashboard/waitlist': typeof DashboardWaitlistRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/project/$projectId/$slug': typeof DashboardProjectProjectIdSlugRouteWithChildren
  '/dashboard/project/$projectId/$slug/changelog': typeof DashboardProjectProjectIdSlugChangelogRoute
  '/dashboard/project/$projectId/$slug/complaints': typeof DashboardProjectProjectIdSlugComplaintsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/changelog/$slug'
    | '/dashboard/stats'
    | '/dashboard/waitlist'
    | '/dashboard/'
    | '/dashboard/project/$projectId/$slug'
    | '/dashboard/project/$projectId/$slug/changelog'
    | '/dashboard/project/$projectId/$slug/complaints'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/changelog/$slug'
    | '/dashboard/stats'
    | '/dashboard/waitlist'
    | '/dashboard'
    | '/dashboard/project/$projectId/$slug'
    | '/dashboard/project/$projectId/$slug/changelog'
    | '/dashboard/project/$projectId/$slug/complaints'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/changelog/$slug'
    | '/dashboard/stats'
    | '/dashboard/waitlist'
    | '/dashboard/'
    | '/dashboard/project/$projectId/$slug'
    | '/dashboard/project/$projectId/$slug/changelog'
    | '/dashboard/project/$projectId/$slug/complaints'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ChangelogSlugRoute: typeof ChangelogSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/waitlist': {
      id: '/dashboard/waitlist'
      path: '/waitlist'
      fullPath: '/dashboard/waitlist'
      preLoaderRoute: typeof DashboardWaitlistRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/stats': {
      id: '/dashboard/stats'
      path: '/stats'
      fullPath: '/dashboard/stats'
      preLoaderRoute: typeof DashboardStatsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/changelog/$slug': {
      id: '/changelog/$slug'
      path: '/changelog/$slug'
      fullPath: '/changelog/$slug'
      preLoaderRoute: typeof ChangelogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/project/$projectId/$slug': {
      id: '/dashboard/project/$projectId/$slug'
      path: '/project/$projectId/$slug'
      fullPath: '/dashboard/project/$projectId/$slug'
      preLoaderRoute: typeof DashboardProjectProjectIdSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/project/$projectId/$slug/complaints': {
      id: '/dashboard/project/$projectId/$slug/complaints'
      path: '/complaints'
      fullPath: '/dashboard/project/$projectId/$slug/complaints'
      preLoaderRoute: typeof DashboardProjectProjectIdSlugComplaintsRouteImport
      parentRoute: typeof DashboardProjectProjectIdSlugRoute
    }
    '/dashboard/project/$projectId/$slug/changelog': {
      id: '/dashboard/project/$projectId/$slug/changelog'
      path: '/changelog'
      fullPath: '/dashboard/project/$projectId/$slug/changelog'
      preLoaderRoute: typeof DashboardProjectProjectIdSlugChangelogRouteImport
      parentRoute: typeof DashboardProjectProjectIdSlugRoute
    }
  }
}

interface DashboardProjectProjectIdSlugRouteChildren {
  DashboardProjectProjectIdSlugChangelogRoute: typeof DashboardProjectProjectIdSlugChangelogRoute
  DashboardProjectProjectIdSlugComplaintsRoute: typeof DashboardProjectProjectIdSlugComplaintsRoute
}

const DashboardProjectProjectIdSlugRouteChildren: DashboardProjectProjectIdSlugRouteChildren =
  {
    DashboardProjectProjectIdSlugChangelogRoute:
      DashboardProjectProjectIdSlugChangelogRoute,
    DashboardProjectProjectIdSlugComplaintsRoute:
      DashboardProjectProjectIdSlugComplaintsRoute,
  }

const DashboardProjectProjectIdSlugRouteWithChildren =
  DashboardProjectProjectIdSlugRoute._addFileChildren(
    DashboardProjectProjectIdSlugRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardStatsRoute: typeof DashboardStatsRoute
  DashboardWaitlistRoute: typeof DashboardWaitlistRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProjectProjectIdSlugRoute: typeof DashboardProjectProjectIdSlugRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardStatsRoute: DashboardStatsRoute,
  DashboardWaitlistRoute: DashboardWaitlistRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProjectProjectIdSlugRoute:
    DashboardProjectProjectIdSlugRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ChangelogSlugRoute: ChangelogSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
