/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as PProjectSlugRouteImport } from './routes/p.$projectSlug'
import { Route as DashboardWaitlistRouteImport } from './routes/dashboard.waitlist'
import { Route as DashboardStatsRouteImport } from './routes/dashboard.stats'
import { Route as DashboardMcpRouteImport } from './routes/dashboard.mcp'
import { Route as ChangelogSlugRouteImport } from './routes/changelog.$slug'
import { Route as PProjectSlugIndexRouteImport } from './routes/p.$projectSlug.index'
import { Route as DashboardProjectProjectIdSlugRouteImport } from './routes/dashboard.project.$projectId.$slug'
import { Route as DashboardProjectProjectIdSlugIndexRouteImport } from './routes/dashboard.project.$projectId.$slug.index'
import { Route as PProjectSlugRRequestIdRequestSlugRouteImport } from './routes/p.$projectSlug.r.$requestId.$requestSlug'
import { Route as DashboardProjectProjectIdSlugRoadmapRouteImport } from './routes/dashboard.project.$projectId.$slug.roadmap'
import { Route as DashboardProjectProjectIdSlugRequestsRouteImport } from './routes/dashboard.project.$projectId.$slug.requests'
import { Route as DashboardProjectProjectIdSlugComplaintsRouteImport } from './routes/dashboard.project.$projectId.$slug.complaints'
import { Route as DashboardProjectProjectIdSlugChangelogRouteImport } from './routes/dashboard.project.$projectId.$slug.changelog'
import { Route as ApiProjectProjectIdWhatsNewExistsRouteImport } from './routes/api.project.$projectId.whats-new.exists'

const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PProjectSlugRoute = PProjectSlugRouteImport.update({
  id: '/p/$projectSlug',
  path: '/p/$projectSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWaitlistRoute = DashboardWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStatsRoute = DashboardStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMcpRoute = DashboardMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => DashboardRoute,
} as any)
const ChangelogSlugRoute = ChangelogSlugRouteImport.update({
  id: '/changelog/$slug',
  path: '/changelog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectSlugIndexRoute = PProjectSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectSlugRoute,
} as any)
const DashboardProjectProjectIdSlugRoute =
  DashboardProjectProjectIdSlugRouteImport.update({
    id: '/project/$projectId/$slug',
    path: '/project/$projectId/$slug',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProjectProjectIdSlugIndexRoute =
  DashboardProjectProjectIdSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProjectProjectIdSlugRoute,
  } as any)
const PProjectSlugRRequestIdRequestSlugRoute =
  PProjectSlugRRequestIdRequestSlugRouteImport.update({
    id: '/r/$requestId/$requestSlug',
    path: '/r/$requestId/$requestSlug',
    getParentRoute: () => PProjectSlugRoute,
  } as any)
const DashboardProjectProjectIdSlugRoadmapRoute =
  DashboardProjectProjectIdSlugRoadmapRouteImport.update({
    id: '/roadmap',
    path: '/roadmap',
    getParentRoute: () => DashboardProjectProjectIdSlugRoute,
  } as any)
const DashboardProjectProjectIdSlugRequestsRoute =
  DashboardProjectProjectIdSlugRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => DashboardProjectProjectIdSlugRoute,
  } as any)
const DashboardProjectProjectIdSlugComplaintsRoute =
  DashboardProjectProjectIdSlugComplaintsRouteImport.update({
    id: '/complaints',
    path: '/complaints',
    getParentRoute: () => DashboardProjectProjectIdSlugRoute,
  } as any)
const DashboardProjectProjectIdSlugChangelogRoute =
  DashboardProjectProjectIdSlugChangelogRouteImport.update({
    id: '/changelog',
    path: '/changelog',
    getParentRoute: () => DashboardProjectProjectIdSlugRoute,
  } as any)
const ApiProjectProjectIdWhatsNewExistsRoute =
  ApiProjectProjectIdWhatsNewExistsRouteImport.update({
    id: '/api/project/$projectId/whats-new/exists',
    path: '/api/project/$projectId/whats-new/exists',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/embed': typeof EmbedRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/dashboard/mcp': typeof DashboardMcpRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/dashboard/waitlist': typeof DashboardWaitlistRoute
  '/p/$projectSlug': typeof PProjectSlugRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/p/$projectSlug/': typeof PProjectSlugIndexRoute
  '/dashboard/project/$projectId/$slug': typeof DashboardProjectProjectIdSlugRouteWithChildren
  '/api/project/$projectId/whats-new/exists': typeof ApiProjectProjectIdWhatsNewExistsRoute
  '/dashboard/project/$projectId/$slug/changelog': typeof DashboardProjectProjectIdSlugChangelogRoute
  '/dashboard/project/$projectId/$slug/complaints': typeof DashboardProjectProjectIdSlugComplaintsRoute
  '/dashboard/project/$projectId/$slug/requests': typeof DashboardProjectProjectIdSlugRequestsRoute
  '/dashboard/project/$projectId/$slug/roadmap': typeof DashboardProjectProjectIdSlugRoadmapRoute
  '/p/$projectSlug/r/$requestId/$requestSlug': typeof PProjectSlugRRequestIdRequestSlugRoute
  '/dashboard/project/$projectId/$slug/': typeof DashboardProjectProjectIdSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/embed': typeof EmbedRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/dashboard/mcp': typeof DashboardMcpRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/dashboard/waitlist': typeof DashboardWaitlistRoute
  '/dashboard': typeof DashboardIndexRoute
  '/p/$projectSlug': typeof PProjectSlugIndexRoute
  '/api/project/$projectId/whats-new/exists': typeof ApiProjectProjectIdWhatsNewExistsRoute
  '/dashboard/project/$projectId/$slug/changelog': typeof DashboardProjectProjectIdSlugChangelogRoute
  '/dashboard/project/$projectId/$slug/complaints': typeof DashboardProjectProjectIdSlugComplaintsRoute
  '/dashboard/project/$projectId/$slug/requests': typeof DashboardProjectProjectIdSlugRequestsRoute
  '/dashboard/project/$projectId/$slug/roadmap': typeof DashboardProjectProjectIdSlugRoadmapRoute
  '/p/$projectSlug/r/$requestId/$requestSlug': typeof PProjectSlugRRequestIdRequestSlugRoute
  '/dashboard/project/$projectId/$slug': typeof DashboardProjectProjectIdSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/embed': typeof EmbedRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/dashboard/mcp': typeof DashboardMcpRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/dashboard/waitlist': typeof DashboardWaitlistRoute
  '/p/$projectSlug': typeof PProjectSlugRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/p/$projectSlug/': typeof PProjectSlugIndexRoute
  '/dashboard/project/$projectId/$slug': typeof DashboardProjectProjectIdSlugRouteWithChildren
  '/api/project/$projectId/whats-new/exists': typeof ApiProjectProjectIdWhatsNewExistsRoute
  '/dashboard/project/$projectId/$slug/changelog': typeof DashboardProjectProjectIdSlugChangelogRoute
  '/dashboard/project/$projectId/$slug/complaints': typeof DashboardProjectProjectIdSlugComplaintsRoute
  '/dashboard/project/$projectId/$slug/requests': typeof DashboardProjectProjectIdSlugRequestsRoute
  '/dashboard/project/$projectId/$slug/roadmap': typeof DashboardProjectProjectIdSlugRoadmapRoute
  '/p/$projectSlug/r/$requestId/$requestSlug': typeof PProjectSlugRRequestIdRequestSlugRoute
  '/dashboard/project/$projectId/$slug/': typeof DashboardProjectProjectIdSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/embed'
    | '/changelog/$slug'
    | '/dashboard/mcp'
    | '/dashboard/stats'
    | '/dashboard/waitlist'
    | '/p/$projectSlug'
    | '/dashboard/'
    | '/p/$projectSlug/'
    | '/dashboard/project/$projectId/$slug'
    | '/api/project/$projectId/whats-new/exists'
    | '/dashboard/project/$projectId/$slug/changelog'
    | '/dashboard/project/$projectId/$slug/complaints'
    | '/dashboard/project/$projectId/$slug/requests'
    | '/dashboard/project/$projectId/$slug/roadmap'
    | '/p/$projectSlug/r/$requestId/$requestSlug'
    | '/dashboard/project/$projectId/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/embed'
    | '/changelog/$slug'
    | '/dashboard/mcp'
    | '/dashboard/stats'
    | '/dashboard/waitlist'
    | '/dashboard'
    | '/p/$projectSlug'
    | '/api/project/$projectId/whats-new/exists'
    | '/dashboard/project/$projectId/$slug/changelog'
    | '/dashboard/project/$projectId/$slug/complaints'
    | '/dashboard/project/$projectId/$slug/requests'
    | '/dashboard/project/$projectId/$slug/roadmap'
    | '/p/$projectSlug/r/$requestId/$requestSlug'
    | '/dashboard/project/$projectId/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/embed'
    | '/changelog/$slug'
    | '/dashboard/mcp'
    | '/dashboard/stats'
    | '/dashboard/waitlist'
    | '/p/$projectSlug'
    | '/dashboard/'
    | '/p/$projectSlug/'
    | '/dashboard/project/$projectId/$slug'
    | '/api/project/$projectId/whats-new/exists'
    | '/dashboard/project/$projectId/$slug/changelog'
    | '/dashboard/project/$projectId/$slug/complaints'
    | '/dashboard/project/$projectId/$slug/requests'
    | '/dashboard/project/$projectId/$slug/roadmap'
    | '/p/$projectSlug/r/$requestId/$requestSlug'
    | '/dashboard/project/$projectId/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EmbedRoute: typeof EmbedRoute
  ChangelogSlugRoute: typeof ChangelogSlugRoute
  PProjectSlugRoute: typeof PProjectSlugRouteWithChildren
  ApiProjectProjectIdWhatsNewExistsRoute: typeof ApiProjectProjectIdWhatsNewExistsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/p/$projectSlug': {
      id: '/p/$projectSlug'
      path: '/p/$projectSlug'
      fullPath: '/p/$projectSlug'
      preLoaderRoute: typeof PProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/waitlist': {
      id: '/dashboard/waitlist'
      path: '/waitlist'
      fullPath: '/dashboard/waitlist'
      preLoaderRoute: typeof DashboardWaitlistRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/stats': {
      id: '/dashboard/stats'
      path: '/stats'
      fullPath: '/dashboard/stats'
      preLoaderRoute: typeof DashboardStatsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mcp': {
      id: '/dashboard/mcp'
      path: '/mcp'
      fullPath: '/dashboard/mcp'
      preLoaderRoute: typeof DashboardMcpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/changelog/$slug': {
      id: '/changelog/$slug'
      path: '/changelog/$slug'
      fullPath: '/changelog/$slug'
      preLoaderRoute: typeof ChangelogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectSlug/': {
      id: '/p/$projectSlug/'
      path: '/'
      fullPath: '/p/$projectSlug/'
      preLoaderRoute: typeof PProjectSlugIndexRouteImport
      parentRoute: typeof PProjectSlugRoute
    }
    '/dashboard/project/$projectId/$slug': {
      id: '/dashboard/project/$projectId/$slug'
      path: '/project/$projectId/$slug'
      fullPath: '/dashboard/project/$projectId/$slug'
      preLoaderRoute: typeof DashboardProjectProjectIdSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/project/$projectId/$slug/': {
      id: '/dashboard/project/$projectId/$slug/'
      path: '/'
      fullPath: '/dashboard/project/$projectId/$slug/'
      preLoaderRoute: typeof DashboardProjectProjectIdSlugIndexRouteImport
      parentRoute: typeof DashboardProjectProjectIdSlugRoute
    }
    '/p/$projectSlug/r/$requestId/$requestSlug': {
      id: '/p/$projectSlug/r/$requestId/$requestSlug'
      path: '/r/$requestId/$requestSlug'
      fullPath: '/p/$projectSlug/r/$requestId/$requestSlug'
      preLoaderRoute: typeof PProjectSlugRRequestIdRequestSlugRouteImport
      parentRoute: typeof PProjectSlugRoute
    }
    '/dashboard/project/$projectId/$slug/roadmap': {
      id: '/dashboard/project/$projectId/$slug/roadmap'
      path: '/roadmap'
      fullPath: '/dashboard/project/$projectId/$slug/roadmap'
      preLoaderRoute: typeof DashboardProjectProjectIdSlugRoadmapRouteImport
      parentRoute: typeof DashboardProjectProjectIdSlugRoute
    }
    '/dashboard/project/$projectId/$slug/requests': {
      id: '/dashboard/project/$projectId/$slug/requests'
      path: '/requests'
      fullPath: '/dashboard/project/$projectId/$slug/requests'
      preLoaderRoute: typeof DashboardProjectProjectIdSlugRequestsRouteImport
      parentRoute: typeof DashboardProjectProjectIdSlugRoute
    }
    '/dashboard/project/$projectId/$slug/complaints': {
      id: '/dashboard/project/$projectId/$slug/complaints'
      path: '/complaints'
      fullPath: '/dashboard/project/$projectId/$slug/complaints'
      preLoaderRoute: typeof DashboardProjectProjectIdSlugComplaintsRouteImport
      parentRoute: typeof DashboardProjectProjectIdSlugRoute
    }
    '/dashboard/project/$projectId/$slug/changelog': {
      id: '/dashboard/project/$projectId/$slug/changelog'
      path: '/changelog'
      fullPath: '/dashboard/project/$projectId/$slug/changelog'
      preLoaderRoute: typeof DashboardProjectProjectIdSlugChangelogRouteImport
      parentRoute: typeof DashboardProjectProjectIdSlugRoute
    }
    '/api/project/$projectId/whats-new/exists': {
      id: '/api/project/$projectId/whats-new/exists'
      path: '/api/project/$projectId/whats-new/exists'
      fullPath: '/api/project/$projectId/whats-new/exists'
      preLoaderRoute: typeof ApiProjectProjectIdWhatsNewExistsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardProjectProjectIdSlugRouteChildren {
  DashboardProjectProjectIdSlugChangelogRoute: typeof DashboardProjectProjectIdSlugChangelogRoute
  DashboardProjectProjectIdSlugComplaintsRoute: typeof DashboardProjectProjectIdSlugComplaintsRoute
  DashboardProjectProjectIdSlugRequestsRoute: typeof DashboardProjectProjectIdSlugRequestsRoute
  DashboardProjectProjectIdSlugRoadmapRoute: typeof DashboardProjectProjectIdSlugRoadmapRoute
  DashboardProjectProjectIdSlugIndexRoute: typeof DashboardProjectProjectIdSlugIndexRoute
}

const DashboardProjectProjectIdSlugRouteChildren: DashboardProjectProjectIdSlugRouteChildren =
  {
    DashboardProjectProjectIdSlugChangelogRoute:
      DashboardProjectProjectIdSlugChangelogRoute,
    DashboardProjectProjectIdSlugComplaintsRoute:
      DashboardProjectProjectIdSlugComplaintsRoute,
    DashboardProjectProjectIdSlugRequestsRoute:
      DashboardProjectProjectIdSlugRequestsRoute,
    DashboardProjectProjectIdSlugRoadmapRoute:
      DashboardProjectProjectIdSlugRoadmapRoute,
    DashboardProjectProjectIdSlugIndexRoute:
      DashboardProjectProjectIdSlugIndexRoute,
  }

const DashboardProjectProjectIdSlugRouteWithChildren =
  DashboardProjectProjectIdSlugRoute._addFileChildren(
    DashboardProjectProjectIdSlugRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardMcpRoute: typeof DashboardMcpRoute
  DashboardStatsRoute: typeof DashboardStatsRoute
  DashboardWaitlistRoute: typeof DashboardWaitlistRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProjectProjectIdSlugRoute: typeof DashboardProjectProjectIdSlugRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardMcpRoute: DashboardMcpRoute,
  DashboardStatsRoute: DashboardStatsRoute,
  DashboardWaitlistRoute: DashboardWaitlistRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProjectProjectIdSlugRoute:
    DashboardProjectProjectIdSlugRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PProjectSlugRouteChildren {
  PProjectSlugIndexRoute: typeof PProjectSlugIndexRoute
  PProjectSlugRRequestIdRequestSlugRoute: typeof PProjectSlugRRequestIdRequestSlugRoute
}

const PProjectSlugRouteChildren: PProjectSlugRouteChildren = {
  PProjectSlugIndexRoute: PProjectSlugIndexRoute,
  PProjectSlugRRequestIdRequestSlugRoute:
    PProjectSlugRRequestIdRequestSlugRoute,
}

const PProjectSlugRouteWithChildren = PProjectSlugRoute._addFileChildren(
  PProjectSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EmbedRoute: EmbedRoute,
  ChangelogSlugRoute: ChangelogSlugRoute,
  PProjectSlugRoute: PProjectSlugRouteWithChildren,
  ApiProjectProjectIdWhatsNewExistsRoute:
    ApiProjectProjectIdWhatsNewExistsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
